/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecibosRouteImport } from './routes/recibos'
import { Route as InadimplenciaRouteImport } from './routes/inadimplencia'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InquilinosIndexRouteImport } from './routes/inquilinos.index'
import { Route as ExInquilinosIndexRouteImport } from './routes/ex-inquilinos.index'
import { Route as InquilinosIdRouteImport } from './routes/inquilinos.$id'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'
import { Route as ExInquilinosIdRouteImport } from './routes/ex-inquilinos.$id'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecibosRoute = RecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => rootRouteImport,
} as any)
const InadimplenciaRoute = InadimplenciaRouteImport.update({
  id: '/inadimplencia',
  path: '/inadimplencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquilinosIndexRoute = InquilinosIndexRouteImport.update({
  id: '/inquilinos/',
  path: '/inquilinos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExInquilinosIndexRoute = ExInquilinosIndexRouteImport.update({
  id: '/ex-inquilinos/',
  path: '/ex-inquilinos/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquilinosIdRoute = InquilinosIdRouteImport.update({
  id: '/inquilinos/$id',
  path: '/inquilinos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ImoveisRoute,
} as any)
const ExInquilinosIdRoute = ExInquilinosIdRouteImport.update({
  id: '/ex-inquilinos/$id',
  path: '/ex-inquilinos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/calendario': typeof CalendarioRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/inadimplencia': typeof InadimplenciaRoute
  '/recibos': typeof RecibosRoute
  '/relatorios': typeof RelatoriosRoute
  '/whatsapp': typeof WhatsappRoute
  '/ex-inquilinos/$id': typeof ExInquilinosIdRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/inquilinos/$id': typeof InquilinosIdRoute
  '/ex-inquilinos/': typeof ExInquilinosIndexRoute
  '/inquilinos/': typeof InquilinosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/calendario': typeof CalendarioRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/inadimplencia': typeof InadimplenciaRoute
  '/recibos': typeof RecibosRoute
  '/relatorios': typeof RelatoriosRoute
  '/whatsapp': typeof WhatsappRoute
  '/ex-inquilinos/$id': typeof ExInquilinosIdRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/inquilinos/$id': typeof InquilinosIdRoute
  '/ex-inquilinos': typeof ExInquilinosIndexRoute
  '/inquilinos': typeof InquilinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/calendario': typeof CalendarioRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/inadimplencia': typeof InadimplenciaRoute
  '/recibos': typeof RecibosRoute
  '/relatorios': typeof RelatoriosRoute
  '/whatsapp': typeof WhatsappRoute
  '/ex-inquilinos/$id': typeof ExInquilinosIdRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/inquilinos/$id': typeof InquilinosIdRoute
  '/ex-inquilinos/': typeof ExInquilinosIndexRoute
  '/inquilinos/': typeof InquilinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/assistente'
    | '/calendario'
    | '/contratos'
    | '/crm'
    | '/financeiro'
    | '/imoveis'
    | '/inadimplencia'
    | '/recibos'
    | '/relatorios'
    | '/whatsapp'
    | '/ex-inquilinos/$id'
    | '/imoveis/$id'
    | '/inquilinos/$id'
    | '/ex-inquilinos/'
    | '/inquilinos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/assistente'
    | '/calendario'
    | '/contratos'
    | '/crm'
    | '/financeiro'
    | '/imoveis'
    | '/inadimplencia'
    | '/recibos'
    | '/relatorios'
    | '/whatsapp'
    | '/ex-inquilinos/$id'
    | '/imoveis/$id'
    | '/inquilinos/$id'
    | '/ex-inquilinos'
    | '/inquilinos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alertas'
    | '/assistente'
    | '/calendario'
    | '/contratos'
    | '/crm'
    | '/financeiro'
    | '/imoveis'
    | '/inadimplencia'
    | '/recibos'
    | '/relatorios'
    | '/whatsapp'
    | '/ex-inquilinos/$id'
    | '/imoveis/$id'
    | '/inquilinos/$id'
    | '/ex-inquilinos/'
    | '/inquilinos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlertasRoute: typeof AlertasRoute
  AssistenteRoute: typeof AssistenteRoute
  CalendarioRoute: typeof CalendarioRoute
  ContratosRoute: typeof ContratosRoute
  CrmRoute: typeof CrmRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
  InadimplenciaRoute: typeof InadimplenciaRoute
  RecibosRoute: typeof RecibosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  WhatsappRoute: typeof WhatsappRoute
  ExInquilinosIdRoute: typeof ExInquilinosIdRoute
  InquilinosIdRoute: typeof InquilinosIdRoute
  ExInquilinosIndexRoute: typeof ExInquilinosIndexRoute
  InquilinosIndexRoute: typeof InquilinosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibos': {
      id: '/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof RecibosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inadimplencia': {
      id: '/inadimplencia'
      path: '/inadimplencia'
      fullPath: '/inadimplencia'
      preLoaderRoute: typeof InadimplenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquilinos/': {
      id: '/inquilinos/'
      path: '/inquilinos'
      fullPath: '/inquilinos/'
      preLoaderRoute: typeof InquilinosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ex-inquilinos/': {
      id: '/ex-inquilinos/'
      path: '/ex-inquilinos'
      fullPath: '/ex-inquilinos/'
      preLoaderRoute: typeof ExInquilinosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquilinos/$id': {
      id: '/inquilinos/$id'
      path: '/inquilinos/$id'
      fullPath: '/inquilinos/$id'
      preLoaderRoute: typeof InquilinosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/ex-inquilinos/$id': {
      id: '/ex-inquilinos/$id'
      path: '/ex-inquilinos/$id'
      fullPath: '/ex-inquilinos/$id'
      preLoaderRoute: typeof ExInquilinosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ImoveisRouteChildren {
  ImoveisIdRoute: typeof ImoveisIdRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisIdRoute: ImoveisIdRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlertasRoute: AlertasRoute,
  AssistenteRoute: AssistenteRoute,
  CalendarioRoute: CalendarioRoute,
  ContratosRoute: ContratosRoute,
  CrmRoute: CrmRoute,
  FinanceiroRoute: FinanceiroRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
  InadimplenciaRoute: InadimplenciaRoute,
  RecibosRoute: RecibosRoute,
  RelatoriosRoute: RelatoriosRoute,
  WhatsappRoute: WhatsappRoute,
  ExInquilinosIdRoute: ExInquilinosIdRoute,
  InquilinosIdRoute: InquilinosIdRoute,
  ExInquilinosIndexRoute: ExInquilinosIndexRoute,
  InquilinosIndexRoute: InquilinosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
